name: run automated tests

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test_and_build:
    name: Test and build samples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: set up JDK
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '11'
      #     distribution: 'temurin'
      - name: run tests
        run: |
        sudo apt update
        sudo apt install openjdk-11-jdk maven
        mvn clean test
